### ISSUE TITLE
Referencing object in Javascript string

### ISSUE THREAD

**Issue by johnreynolds** [leebenson/graphql-with-sequelize#3]
Lee,

This is probably a newbie goof, but I had to replace your inline object reference to create a post with the person's firstName (in db.js)...

// title: 'Sample title by ${person.firstName}',
                title: 'Sample title by ' + person.firstName,

I am using node 6 rather than node 5 - Do you know if I have to add another dependency to get this object reference functionality?

Thanks

**Comment by leebenson** [comment]
Hi @johnreynolds, 

If you're ever wondering which version of Node supports which features, you can check out http://node.green/ for a handy table.

What you're looking for in this case is **template literals** - which you can see has actually been supported since Node 4.3, so Node 6 definitely has you covered.

Just make sure you're using backticks and not single quotes (i.e. **`** and not **'** - to the left of the '1' or the 'z' on a Mac US layout keyboard), and it should work nicely.

Have fun!

**Comment by johnreynolds** [comment]
Back-ticks!
Thanks Lee. You're my new favorite person.

**Comment by leebenson** [comment]
Ha, thanks! Glad I helped 👍
